# Base URL used when generating links to your pages
baseURL = "https://homakaka.github.io"
theme = 'hugo-bearblog'

title = "Minbok Wi"
author = "Minbok Wi"
copyright = "Minbok Wi"
languageCode = "en-US"

enableRobotsTXT = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true

[[menus.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2

[params]
  description = "Minbok Wi's personal website."
