# Base URL used when generating links to your pages
baseURL = "https://homakaka.github.io"
theme = 'hugo-bearblog'

title = "Minbok Wi"
author = "Minbok Wi"
copyright = "Minbok Wi"
locale = "en-US"

enableRobotsTXT = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true

[params]
  description = "Minbok Wi's personal website."
  brand = "위민복 Minbok Wi"
  name = "Minbok Wi"
  role = "Staff Engineer, AP Architecture Group (MX Division), Samsung Electronics"

  [[params.links]]
    name = "CV"
    url = "https://docs.google.com/document/d/13rVSENkJ0MFpxon_ihRkUQhXHW2S-CvXUINBWNVfUMA/edit?usp=sharing"
  [[params.links]]
    name = "Google Scholar"
    url = "https://scholar.google.com/citations?user=3f75zVUAAAAJ"
  [[params.links]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/minbok-wi-9ab99b1b9/"
  [[params.links]]
    name = "GitHub"
    url = "https://github.com/homakaka"
  [[params.links]]
    name = "ORCID"
    url = "https://orcid.org/0000-0003-4202-6201"
